name: Hello World!

on:
  push: 
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"

jobs:
  show_date_job:
    runs-on: ubuntu-20.04
      steps:
        - name: Current date 
          run: |
            echo date

jobs:
  show_dir:
    runs-on: ubuntu-20.04
      steps:
        - name: Current dir
          run: |
            echo ls -l
